// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('app', ['ngRoute', 'app.controllers']).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/home', {
        templateUrl: 'app/partials/home.html',
        controller: 'HomeController'
      });
      $routeProvider.when('/twitter', {
        templateUrl: 'app/partials/irc_rankings.html',
        controller: 'TweetController'
      });
      return $routeProvider.otherwise({
        redirectTo: '/home'
      });
    }
  ]);

}).call(this);
