// Generated by CoffeeScript 1.6.3
(function() {
  var app,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  app = angular.module('app.controllers', ['firebase']);

  app.controller('HomeController', function($scope) {
    $scope.piImage = "/app/img/rpi_logo.jpg";
    $scope.ircImage = "/app/img/robot_icon.png";
    return $scope.siteImage = "/app/img/angularjs.png";
  });

  app.controller('RankController', function($scope, angularFire) {
    var ref;
    $scope.players = new Array();
    ref = new Firebase("https://steamduck.firebaseio.com/players");
    return angularFire(ref, $scope, 'players');
  });

  app.controller('FifaController', function($scope, angularFire) {
    var ref;
    $scope.newMatch;
    $scope.players = {};
    ref = new Firebase("https://steamduck.firebaseio.com/fifa");
    angularFire(ref.child("players"), $scope, 'players');
    $scope.openModal = function() {
      return $(".modal").modal('show');
    };
    return $scope.submit = function() {
      var addPlayerStats, matchOutcome, newPlayer, player, playerFound, winner, _ref;
      if (_ref = $scope.home.PlayerName, __indexOf.call($scope.players, _ref) < 0) {
        player = {};
      }
      $scope.home.goals = parseInt($scope.home.goals);
      $scope.away.goals = parseInt($scope.away.goals);
      matchOutcome = $scope.home.goals - $scope.away.goals;
      winner = matchOutcome === 0 ? "draw" : goalStatus > 0 ? "home" : "away";
      $scope.home.goalsAgainst = $scope.away.goals;
      $scope.away.goalsAgainst = $scope.home.goals;
      newPlayer = {};
      addPlayerStats = function(player, newMatch, didWin) {
        if (player.GoalsFor != null) {
          player.GoalsFor += newMatch.goals;
        } else {
          player.GoalsFor = newMatch.goals;
        }
        if (player.GoalsAgainst != null) {
          player.GoalsAgainst += newMatch.goalsAgainst;
        } else {
          player.GoalsAgainst = newMatch.goalsAgainst;
        }
        if (didWin) {
          if (player.Wins != null) {
            player.Wins += 1;
          } else {
            player.Wins = 1;
          }
          if (player.Points != null) {
            return player.Points += 3;
          } else {
            return player.Points = 3;
          }
        } else {
          if (player.Losses != null) {
            return player.Losses += 1;
          } else {
            return player.Losses = 1;
          }
        }
      };
      playerFound = false;
      $scope.players.forEach(function(player) {
        if (player.PlayerName === $scope.home.name) {
          addPlayerStats(player, $scope.home, winner);
          return playerFound = true;
        }
      });
      if (!playerFound) {
        newPlayer.PlayerName = $scope.home.name;
        addPlayerStats(newPlayer, $scope.home, winner);
        $scope.players.push(newPlayer);
      }
      playerFound = false;
      $scope.players.forEach(function(player) {
        if (player.PlayerName === $scope.away.name) {
          addPlayerStats(player, $scope.away, winner);
          return playerFound = true;
        }
      });
      if (!playerFound) {
        newPlayer.PlayerName = $scope.away.name;
        addPlayerStats(newPlayer, $scope.away, !didHomeWin);
        $scope.players.push(newPlayer);
      }
      $(".modal").modal('hide');
      $scope.home = {};
      return $scope.away = {};
    };
  });

}).call(this);
