// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('app.controllers', ['firebase']);

  app.controller('HomeController', function($scope) {
    $scope.piImage = "/app/img/rpi_logo.jpg";
    $scope.ircImage = "/app/img/robot_icon.png";
    return $scope.siteImage = "/app/img/angularjs.png";
  });

  app.controller('RankController', function($scope, angularFire) {
    var ref;
    $scope.players = new Array();
    ref = new Firebase("https://steamduck.firebaseio.com/players");
    return angularFire(ref, $scope, 'players');
  });

  app.controller('FifaController', function($scope, angularFire) {
    var ref;
    $scope.newMatch;
    $scope.players = new Array();
    ref = new Firebase("https://steamduck.firebaseio.com/fifa");
    angularFire(ref.child("players"), $scope, 'players');
    $scope.openModal = function() {
      return $(".modal").modal('show');
    };
    return $scope.submit = function() {
      var awayPlayer, awayPlayerFound, goalStatus, homePlayer, homePlayerFound, newAwayPlayer, newHomePlayer;
      homePlayer = {};
      awayPlayer = {};
      newHomePlayer = {};
      newAwayPlayer = {};
      homePlayer.goalsFor = parseInt($scope.home.goals);
      homePlayer.goalsAgainst = parseInt($scope.away.goals);
      awayPlayer.goalsFor = parseInt($scope.away.goals);
      awayPlayer.goalsAgainst = parseInt($scope.home.goals);
      goalStatus = $scope.home.goals - $scope.away.goals;
      homePlayerFound = false;
      awayPlayerFound = false;
      $scope.players.forEach(function(player) {
        player.Draw += goalStatus === 0 ? 1 : 0;
        if (player.PlayerName === $scope.home.name) {
          homePlayerFound = true;
          player.Wins += goalStatus > 0 ? 1 : 0;
          player.Loss += goalStatus < 0 ? 1 : 0;
          player.goalsFor += homePlayer.goalsFor;
          return player.goalsAgainst += homePlayer.goalsAgainst;
        } else if (player.PlayerName === $scope.away.name) {
          awayPlayerFound = true;
          player.Wins += goalStatus < 0 ? 1 : 0;
          player.Loss += goalStatus > 0 ? 1 : 0;
          player.goalsFor += awayPlayer.goalsFor;
          return player.goalsAgainst += awayPlayer.goalsAgainst;
        }
      });
      if (!awayPlayerFound) {
        newAwayPlayer.PlayerName = $scope.away.name;
        newAwayPlayer.Wins = goalStatus < 0 ? 1 : 0;
        newAwayPlayer.Loss = goalStatus > 0 ? 1 : 0;
        newAwayPlayer.Draw = goalStatus === 0 ? 1 : 0;
        newAwayPlayer.goalsFor = awayPlayer.goalsFor;
        newAwayPlayer.goalsAgainst = awayPlayer.goalsAgainst;
        $scope.players.push(newAwayPlayer);
      }
      if (!homePlayerFound) {
        newHomePlayer.PlayerName = $scope.home.name;
        newHomePlayer.Wins = goalStatus > 0 ? 1 : 0;
        newHomePlayer.Loss = goalStatus < 0 ? 1 : 0;
        newHomePlayer.Draw = goalStatus === 0 ? 1 : 0;
        newHomePlayer.goalsFor += homePlayer.goalsFor;
        newHomePlayer.goalsAgainst += homePlayer.goalsAgainst;
        $scope.players.push(newHomePlayer);
      }
      $(".modal").modal('hide');
      $scope.home = {};
      return $scope.away = {};
    };
  });

}).call(this);
