// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('app.filters', []);

  app.filter("orderObjectBy", function() {
    return function(input, attribute) {
      var array, objectKey;
      if (!angular.isObject(input)) {
        return input;
      }
      array = [];
      for (objectKey in input) {
        array.push(input[objectKey]);
      }
      return array.sort(function(a, b) {
        a = parseInt(a[attribute]);
        b = parseInt(b[attribute]);
        return b - a;
      });
    };
  });

}).call(this);
